# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      - TOKEN: "5bcc1fa47397ddc036e3575fec31517f80e1c769"

    working_directory: ~/AppiumTest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - restore_cache:
          keys:
          - allure-report

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo pip3 install Appium-Python-Client
            sudo pip3 install allure-pytest
#            sudo apt-get install unzip
#            wget -O allure-2.5.0.zip https://bintray.com/qameta/generic/download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.5.0%2Fallure-2.5.0.zip
#            unzip allure-2.5.0.zip

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest android_simple.py --alluredir test-report/
#            python3 run_env.py

      # save allure package and the last html allure report cache
      - save_cache:
          key: allure-report-{{ checksum "test-reports.tar.gz" }}
          paths:
              - ./allure-2.5.0
              - ./test-reports.tar.gz
              - ./test-report.tar.gz


      - store_artifacts:
          path: test-reports
          destination: test-reports
